// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifhwuoewayfsffyxesbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmaHd1b2V3YXlmc2ZmeXhlc2JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDM5MDEsImV4cCI6MjA2NTUxOTkwMX0.PCP-RAxOu550ibqSfDvpUtJj7p2pWqKupbCyV89DxPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);